<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="7" total="8" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-03-20T19:38:29 PDT" name="Default suite" finished-at="2024-03-20T19:38:31 PDT" duration-ms="2465">
    <groups>
    </groups>
    <test started-at="2024-03-20T19:38:29 PDT" name="Default test" finished-at="2024-03-20T19:38:31 PDT" duration-ms="2465">
      <class name="org.GitHub.CRUD.GitHub">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:org.GitHub.CRUD.GitHub@3835c46]" started-at="2024-03-20T19:38:29 PDT" name="beforeSuite" finished-at="2024-03-20T19:38:29 PDT" duration-ms="74" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="setup()[pri:0, instance:org.GitHub.CRUD.GitHub@3835c46]" started-at="2024-03-20T19:38:29 PDT" name="setup" finished-at="2024-03-20T19:38:30 PDT" duration-ms="411" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="beforeClass()[pri:0, instance:org.GitHub.CRUD.GitHub@3835c46]" started-at="2024-03-20T19:38:30 PDT" name="beforeClass" finished-at="2024-03-20T19:38:30 PDT" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method signature="validateDeleteData()[pri:0, instance:org.GitHub.CRUD.GitHub@3835c46]" started-at="2024-03-20T19:38:30 PDT" name="validateDeleteData" finished-at="2024-03-20T19:38:31 PDT" duration-ms="1717" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Delete data functionality is not working as expected. expected [204] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Delete data functionality is not working as expected. expected [204] but found [404]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1418)
at org.testng.Assert.assertEquals(Assert.java:1382)
at org.GitHub.CRUD.GitHub.validateDeleteData(GitHub.java:168)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validateDeleteData -->
      </class> <!-- org.GitHub.CRUD.GitHub -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
